let numClick=-1;
let userPattern=[];
let correctPattern=[];
let possibleColors=["red","blue","yellow","green"];
let level=0;
let highscore=0;

// to make a sound and animation when we ourselves click the button and also cheack answer
$(".button").click(function(buttonClicked){
    numClick++;
    let color=buttonClicked.target.id;
    clickAnimation("#"+color);
    playAudio(color);
    cheackAnswer(color);
});

function cheackAnswer(color){
userPattern.push(color);
if(color==correctPattern[numClick]){
    if(userPattern.length==correctPattern.length){
        setTimeout(function(){
            userPattern=[];
            numClick=-1;
            nextSequence();
        },1000);
    }
    else{

    }
}

else{
    $("h2").text("Game over ! Hit another key to try again !");
    userPattern=[];
    correctPattern=[];
    if(level>highscore){
        highscore=level;
        $("#highscore").text(level);
    }
    playAudio("wrong");
    level=0;
    numClick=-1;
}
}







// to generate random color
function nextSequence(){
    level++;
    $("#level").text(level);
    let rand=Math.floor(Math.random()*4)
    let color=possibleColors[rand];
   correctPattern.push(color);
   playAudio(color);
   clickAnimation("#"+color);
}

// to play audio when color is generated
function playAudio(color){
    let relPath=`sounds/${color}.mp3`;
    let audio=new Audio(relPath);
    audio.play();
}

// to show which color is generated by computer or which color you have to chose
function clickAnimation(id){
    $(id).fadeOut(100).fadeIn(100);
}





// when any key is pressed in document
$(document).keydown(function(){
    if(level<=0){
        $("h2").text("The Game begins !")
        nextSequence();
    }
});


// $("#red").css("background-color","white");

